import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Header from './components/Header'
import local from "next/font/local";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const robotoMono = localFont({
  src: "./fonts/RobotoMono-Light.ttf",
  variable: "--font-roboto-mono",
  weight: "100 900",
});

const zenkakuGothicLight = localFont({
  src: "./fonts/ZenKakuGothicAntique-Light.ttf",
  variable: "--font-zenkaku-gothic-light",
  weight: "100 900",
});
const zenkakuGothicMedium = localFont({
  src: "./fonts/ZenKakuGothicAntique-Medium.ttf",
  variable: "--font-zenkaku-gothic-medium",
  weight: "100 900",
});
const zenkakuGothicRegular = localFont({
  src: "./fonts/ZenKakuGothicAntique-Regular.ttf",
  variable: "--font-zenkaku-gothic-regular",
  weight: "100 900",
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoMono.variable} ${zenkakuGothicLight.variable} ${zenkakuGothicMedium.variable} ${zenkakuGothicRegular.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
